[project]
name = "mflt-build-id"
version = "1.0.2"
dependencies = [
  "pyelftools >=0.31,<0.32",
]
requires-python = ">=3.8,<4.0"

[tool.uv]
dev-dependencies = [
  "pytest >=6",
  "pytest-cov >=2,<3",
  "pytest-timeout >=2.0,<3.0",
  "wasmer ==0.3.0",
]
